### ISSUE TITLE
nodejs example run failed

### ISSUE THREAD

**Issue by sanmao3** [ONLYOFFICE/document-server-integration#116]
os: Mac
node: v14.15.4
npm: 6.14.10

follow the running steps
`npm install`
`node bin/www`

but it show SyntaxError. How to fix it? Thanks

<img width="714" alt="截屏2021-02-03上午9 53 48" src="https://user-images.githubusercontent.com/5188427/106686722-ce7b7880-6605-11eb-96f3-acb074ceceab.png">

**Comment by LinneyS** [comment]
Fixed in cefcba3b04b540b57e05c756c7560a968127d137
