### ISSUE TITLE
Error on Editor page when opening document 

### ISSUE THREAD

**Issue by abhi5003** [ONLYOFFICE/document-server-integration#192]
I am using feature/change-files-folder branch and i specified the custom storage-folder path in settings.properties but I got this error

![Capture](https://user-images.githubusercontent.com/55706631/133241327-dc5c4d2a-1e45-4fe6-ae31-7ae824f6c087.PNG)

and provide this configuration on settings.properties

![Capture1](https://user-images.githubusercontent.com/55706631/133241559-60ce2653-8b54-4fd3-a272-8a3073f5ca64.PNG)

**Comment by ShockwaveNN** [comment]
> I am using feature/change-files-folder branch 

I'm sorry, why?

I do not even know if this branch is in working condition

**Comment by abhi5003** [comment]
this branch update on 13 sept

**Comment by ShockwaveNN** [comment]
So? I do not understand your logik. This is development branch and can contain any number of not working features and do not work at all

**Comment by olejiksin** [comment]
can you try using your path with \\, not // ?

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
