### ISSUE TITLE
php demo code not working as subpath

### ISSUE THREAD

**Issue by dipenpatel235** [ONLYOFFICE/document-server-integration#24]
hello..
i have downloaded php demo code from below link and create dir inside  webserver's root dir as 'onlyoffice'
https://api.onlyoffice.com/editors/demopreview

Now my URI became 
"https://www.myhost.com/onlyoffice"
so that is not working...

Now if i extract whole code in webserver's root dir then it is working fine.
so  below uri is working
"https://www.myhost.com/"

I am using nginx web server.
Let me know is i am doing anything wrong ?

**Comment by JohnPerkin** [comment]
Hello @dipenpatel235!
We will take the issue into consideration and probably solve in future versions.
Thank you for the interest in ONLYOFFICE.

**Comment by JohnPerkin** [comment]
Hello @dipenpatel235 
To solve the issue please set in [config](https://github.com/ONLYOFFICE/document-server-integration/blob/master/web/documentserver-example/php/config.php#L21)
`$GLOBALS['EXAMPLE_URL'] = "https://www.myhost.com/onlyoffice";`
