### ISSUE TITLE
php demo code not working in windows XAMPP

### ISSUE THREAD

**Issue by dipenpatel235** [ONLYOFFICE/document-server-integration#25]
php demo code not working in windows XAMPP.
let me know if i have did anything wrong.

i have downloaded php example zip  file and extracted on htdocs root dir.
after upload file backend error log is

[Thu Apr 06 12:56:22.159865 2017] [:error] [pid 9928:tid 1620] [client 192.168.0.107:57699] PHP Warning:  move_uploaded_file(): Unable to move 'C:\\xampp\\tmp\\phpAD45.tmp' to 'C:\\xampp\\htdocs\\C:\nmpp\\htdocs\\Collect_data\\192.168.0.107\\my_rank.xlsx' in C:\\xampp\\htdocs\\webeditor-ajax.php on line 109, referer: http://192.168.0.107/

**Comment by JohnPerkin** [comment]
Hello @dipenpatel235!
Please check if you have corresponding rights to the folder `htdoc`

**Comment by JohnPerkin** [comment]
Hello @dipenpatel235!
`STORAGE_PATH` value in [config](https://github.com/ONLYOFFICE/document-server-integration/blob/master/web/documentserver-example/php/config.php#L4) is a relative path. You can't use absolute path there.
