### ISSUE TITLE
[Feature] ask for UpdateToVersionFile Official implementation

### ISSUE THREAD

**Issue by yaolinhong** [ONLYOFFICE/document-server-integration#314]
i was stuck when i want to achieve restore feature.
i think we need an 'UpdateToVersionFileAsync' function example.

after searching organization .i found 'RestoreVersionAsync、UpdateToVersionFileAsync' funciton in Below project.

[url](https://github.com/ONLYOFFICE/DocSpace/blob/15fc78111a6dc0e98d92b3d1fa5359ea664ccea7/products/ASC.Files/Core/Core/FileStorageService.cs)
[url](https://github.com/ONLYOFFICE/DocSpace/blob/15fc78111a6dc0e98d92b3d1fa5359ea664ccea7/products/ASC.Files/Core/Utils/EntryManager.cs#L1211)

can we have an Official implementation for this?
Thank you.

**Comment by Misokados** [comment]
Hello @yaolinhong 
Please clarify your request. What exactly is going wrong?
Do I understand it right that you are trying to implement Document history feature? I mean this one: https://api.onlyoffice.com/editors/history#apply

If so, please note that file versions storage and management is your task as independent integrator. To display the versions list in the editor you have to pass information about versions and version order.
If I misunderstood your request, please clarify it.

**Comment by yaolinhong** [comment]
> Hello @yaolinhong Please clarify your request. What exactly is going wrong? Do I understand it right that you are trying to implement Document history feature? I mean this one: https://api.onlyoffice.com/editors/history#apply
> 
> If so, please note that file versions storage and management is your task as independent integrator. To display the versions list in the editor you have to pass information about versions and version order. If I misunderstood your request, please clarify it.

thanks for the response. @Misokados
i has followed the guide to implement Document history feature. https://api.onlyoffice.com/editors/history#apply
i have no problem about display the versions list in the editor.
when browser trrigger onRequestRestore button,it seems i need to do some file versions storage and management work myself.
I would really appreciate if you can give me some simple advice.

[image](https://user-images.githubusercontent.com/26712987/204414773-52acf0f9-d7de-44b4-9afd-68c308a40f67.png)

**Comment by Misokados** [comment]
> when browser trrigger onRequestRestore button,it seems i need to do some file versions storage and management work myself.

That's right. Please check out this title: https://api.onlyoffice.com/editors/config/events#onRequestRestore
You have to call https://api.onlyoffice.com/editors/methods#refreshHistory when user clicks on 'Restore' button.

**Comment by Misokados** [comment]
So, the ideal scenario should look like this: when a user clicks the 'Restore' button you have to check out number version and place it as the latest version in your storage. After that you have to refresh versions order.
