### ISSUE TITLE
.Net MVC Code Integration With Enterprise Edition

### ISSUE THREAD

**Issue by Anupam750** [ONLYOFFICE/document-server-integration#51]
I downloaded enterprise edition and installed it on Windows Server 2016 and it is working as expected on localhost by default.

===========
but now 

I need to do some customization in this code so I am integrating .Net MVC Code (https://api.onlyoffice.com/editors/demopreview#DemoPreview) with installed enterprise server.

Please suggest me, I have tried with readme file from the source code but that is not working till now.

Please let me know if any other thing other than it.

**Comment by LinneyS** [comment]
You must set [files.docservice.url](https://github.com/ONLYOFFICE/document-server-integration/blob/master/web/documentserver-example/csharp-mvc/web.appsettings.config#L18) in the MVC example configuration file.
Replace `https://documentserver/` to `http://localhost/ds-vpath/` or `http://YOUR-IP/ds-vpath/` to connect to your Document Service of enterprise server.

**Comment by ibnpetr** [comment]
@Anupam750 IIS adds that header `<add name="X-Frame-Options" value="SAMEORIGIN" />`
Please note that if you are going to integrate Document Server into your own service you should use [ONLYOFFICE Developer Server](https://www.onlyoffice.com/developer-edition.aspx)

**Comment by LinneyS** [comment]
Could you please specify if the problem recurs or we can close the topic?

**Comment by LinneyS** [comment]
This issue was closed due to no response.
