### ISSUE TITLE
Question about customization parameter: about

### ISSUE THREAD

**Issue by KenjiOhtsuka** [ONLYOFFICE/document-server-integration#565]
https://github.com/ONLYOFFICE/document-server-integration/blob/333981cdad8553fd7308a3023bcf0f1ca305f5a1/web/documentserver-example/php/src/views/DocEditorView.php#L177

is this a valid customization setting?

I didn't find "about" in Only Office API page, https://api.onlyoffice.com/editors/config/editor/customization .

**Comment by SergeyKorneyev** [comment]
Hello,
This parameter can only be used if you have a Docs Developer Edition license with the extended white label option.

**Comment by KenjiOhtsuka** [comment]
@SergeyKorneyev Thanks, I understood.
