### ISSUE TITLE
erro download - NodeJS

### ISSUE THREAD

**Issue by GlauberF** [ONLYOFFICE/document-server-integration#58]
I'm testing the nodejs integration version and for whatever option the error is the same

![Captura de Tela_selecionar área_20190321215117](https://user-images.githubusercontent.com/11314585/54793924-ab1ece80-4c23-11e9-85bb-33fd4b695920.png)

![Captura de Tela_selecionar área_20190321215424](https://user-images.githubusercontent.com/11314585/54793961-ef11d380-4c23-11e9-989c-09b49d02e80e.png)

![Captura de Tela_selecionar área_20190321215500](https://user-images.githubusercontent.com/11314585/54793969-ffc24980-4c23-11e9-84f6-7918f0bda5da.png)

**Comment by LinneyS** [comment]
You should open the integration example at the address that will be accessible from the Document Server instead of `127.0.0.1`
Or set the setting [exampleUrl](https://github.com/ONLYOFFICE/document-server-integration/blob/develop/web/documentserver-example/nodejs/config/default.json#L21)

**Comment by GlauberF** [comment]
@LinneyS 

I do not understand, I'm new to this.

what do I configure and how do I set the url in exampleUrl?

Is this field mandatory for operation?

**Comment by GlauberF** [comment]
Hello, after many tests I got it.

My question, user IDs can I use from my application, for example (userid = database id & name = User name in database)

Another doubt, I want to intonate S3 from amazon, to search the files and save the reviews and history inside the folder of each user, could help me, how would I do this, where to start?

**Comment by CarlOnlyoffice** [comment]
Hello @GlauberF
Are you trying to use this all in NodeJS integration example? Please note that this is only an example which is used to demonstrate how to integrate Document Server with your application. We strongly recommend to not build your application based on the example without proper code modifications.

If I understood you incorrectly, please provide a more detailed usage scenario.

**Comment by GlauberF** [comment]
Ok, I get it.

Another question I can use in production on my server is the documentserver docker, is it stable and safe to be used in production?
