### ISSUE TITLE
document-server in docker not able to find any documents

### ISSUE THREAD

**Issue by macperez** [ONLYOFFICE/document-server-integration#61]
Dear community, 
I have built a small document-manager python based from [here](https://dzone.com/articles/integrating-onlyoffice-with-a-python-app). 
I also have started a docker container with document-server inside. Nothing mysterious. 
```
docker run -i -t -d -p 80:80 --restart=always \ 
-v /app/onlyoffice/DocumentServer/logs:/var/log/onlyoffice \ 
-v /app/onlyoffice/DocumentServer/data:/var/www/onlyoffice/Data \ 
-v /app/onlyoffice/DocumentServer/lib:/var/lib/onlyoffice \ 
-v /app/onlyoffice/DocumentServer/db:/var/lib/postgresql onlyoffice/documentserver 
```
But when I sent through javascript the id of my document (hosted on my computer) the document-server is not finding anything. The piece of javascript code I used is:

```editor = new DocsAPI.DocEditor("placeholder",
            {
                documentType: "text",
                document: {
                    fileType: "odt",
                    url: "http://localhost:8080/files/ex2.odt",
                    title: filename,
                    key: filename + '_key'
                },
                editorConfig: {mode: 'view'}, 
                height: "100%",
                width: "100%"
            });
```
I ams passing the URL even harcoded but is not finding the document. I've attached the chrome developer console   with the response: 
![not-found](https://user-images.githubusercontent.com/6901541/62763873-e021a580-ba8c-11e9-9dc8-5618b5a8b3e0.jpeg)

Another secundary problem is that I can't see where the logs are placed. In theory, they should be in `/var/log/onlyoffice` but no one file is there. 

Any idea, what's going on?

**Comment by macperez** [comment]
I do not know if you are able to see my screenshot.
![not-found](https://user-images.githubusercontent.com/6901541/62764112-65a55580-ba8d-11e9-9b97-058c9e757288.jpeg)

**Comment by flaminestone** [comment]
Hello @macperez.  Are you still having the problem with example?
You are using localhost inside the docker container, it is not a good idea. You can use  [this](https://github.com/no-flamine/onlyoffice-example-integration-python) example to evade problems of using docker with different ports

**Comment by LinneyS** [comment]
This issue was closed due to no response.

**Comment by JDSalcedo** [comment]
Hi @flaminestone It seems onlyoffice image always have to run on 80 port, even when the documentation says that you can change it. I've cloned your repo and execute `docker-compose up` with this changes:
config.json
`{
  "editor": {
    "protocol": "http",
    "url": "localhost",
    "port": "80"
  },
  "app": {
    "protocol": "http",
    "url": "localhost",
    "port": "7070"
  }
}`

docker-compose.yml
`# IT a docker-compose file for start all palladium services.
version: '3'
services:
  app:
    build: .
    ports:
      - "7070:7070"
    tty: true
    volumes:
      - .:/example
  documentserver:
    image: onlyoffice/documentserver
    ports:
      - "80:80"`

And this is what docker logs shows:
`Starting onlyoffice-example-integration-python_app_1            ... done
Starting onlyoffice-example-integration-python_documentserver_1 ... done
Attaching to onlyoffice-example-integration-python_documentserver_1, onlyoffice-example-integration-python_app_1
app_1             | Bottle v0.12.19 server starting up (using WSGIRefServer())...
app_1             | Listening on http://0.0.0.0:7070/
app_1             | Hit Ctrl-C to quit.
app_1             |
documentserver_1  |  * Starting PostgreSQL 12 database server
documentserver_1  |    ...done.
documentserver_1  |  * Starting RabbitMQ Messaging Server rabbitmq-server
documentserver_1  |    ...done.
documentserver_1  | Starting supervisor: supervisord.
documentserver_1  |  * Starting periodic command scheduler cron
documentserver_1  |    ...done.
documentserver_1  |  * Starting nginx nginx
documentserver_1  |    ...done.
app_1             | 172.19.0.1 - - [01/Apr/2021 02:20:50] "GET / HTTP/1.1" 200 2505
documentserver_1  | Generating AllFonts.js, please wait...Done
app_1             | 172.19.0.1 - - [01/Apr/2021 02:21:39] "GET /favicon.ico HTTP/1.1" 404 742
documentserver_1  | Generating presentation themes, please wait...Done
documentserver_1  | ds:docservice: stopped
documentserver_1  | ds:docservice: started
documentserver_1  | ds:converter: stopped
documentserver_1  | ds:converter: started
documentserver_1  |  * Reloading nginx configuration nginx
documentserver_1  |    ...done.
documentserver_1  | ==> /var/log/onlyoffice/documentserver/converter/err.log <==
documentserver_1  |
documentserver_1  | ==> /var/log/onlyoffice/documentserver/converter/out.log <==
documentserver_1  |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
documentserver_1  | [2021-04-01T02:23:24.408] [ERROR] nodeJS - error downloadFile:url=http://localhost:7070/files/sample.pptx;attempt=2;code:ECONNREFUSED;connect:null;(id=a33e3f9864b14f14e162)
documentserver_1  | Error: connect ECONNREFUSED 127.0.0.1:7070
documentserver_1  |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
documentserver_1  | [2021-04-01T02:23:25.411] [ERROR] nodeJS - error downloadFile:url=http://localhost:7070/files/sample.pptx;attempt=3;code:ECONNREFUSED;connect:null;(id=a33e3f9864b14f14e162)
documentserver_1  | Error: connect ECONNREFUSED 127.0.0.1:7070
documentserver_1  |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
documentserver_1  | [2021-04-01T02:23:30.623] [ERROR] nodeJS - error downloadFile:url=http://localhost:7070/files/sample.docx;attempt=1;code:ECONNREFUSED;connect:null;(id=635ea88559c288a4e6da)
documentserver_1  | Error: connect ECONNREFUSED 127.0.0.1:7070
documentserver_1  |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
documentserver_1  |
documentserver_1  | ==> /var/log/onlyoffice/documentserver/docservice/err.log <==
documentserver_1  |
documentserver_1  | ==> /var/log/onlyoffice/documentserver/docservice/out.log <==
documentserver_1  | [2021-04-01T02:13:15.511] [WARN] nodeJS - Express server listening on port 8000 in production-linux mode. Version: 6.2.0. Build: 123
documentserver_1  | [2021-04-01T02:15:56.420] [WARN] nodeJS - Express server starting...
documentserver_1  | [2021-04-01T02:15:56.423] [WARN] nodeJS - Failed to subscribe to plugin folder updates. When changing the list of plugins, you must restart the server. https://nodejs.org/docs/latest/api/fs.html#fs_availa
bility
documentserver_1  | [2021-04-01T02:15:56.456] [WARN] nodeJS - Express server listening on port 8000 in production-linux mode. Version: 6.2.0. Build: 123
documentserver_1  | [2021-04-01T02:20:53.258] [WARN] nodeJS - Express server starting...
documentserver_1  | [2021-04-01T02:20:53.261] [WARN] nodeJS - Failed to subscribe to plugin folder updates. When changing the list of plugins, you must restart the server. https://nodejs.org/docs/latest/api/fs.html#fs_availa
bility
documentserver_1  | [2021-04-01T02:20:55.387] [WARN] nodeJS - Express server listening on port 8000 in production-linux mode. Version: 6.2.0. Build: 123
documentserver_1  | [2021-04-01T02:23:10.554] [WARN] nodeJS - Express server starting...
documentserver_1  | [2021-04-01T02:23:10.557] [WARN] nodeJS - Failed to subscribe to plugin folder updates. When changing the list of plugins, you must restart the server. https://nodejs.org/docs/latest/api/fs.html#fs_availa
bility
documentserver_1  | [2021-04-01T02:23:10.594] [WARN] nodeJS - Express server listening on port 8000 in production-linux mode. Version: 6.2.0. Build: 123
documentserver_1  |
documentserver_1  | ==> /var/log/onlyoffice/documentserver/metrics/err.log <==
documentserver_1  |
documentserver_1  | ==> /var/log/onlyoffice/documentserver/metrics/out.log <==
documentserver_1  | 1 Apr 01:50:36 - [970] reading config file: ./config/config.js
documentserver_1  | 1 Apr 01:50:37 - server is up INFO
documentserver_1  | 1 Apr 01:55:58 - [997] reading config file: ./config/config.js
documentserver_1  | 1 Apr 01:55:58 - server is up INFO
documentserver_1  | 1 Apr 02:06:40 - [970] reading config file: ./config/config.js
documentserver_1  | 1 Apr 02:06:40 - server is up INFO
documentserver_1  | 1 Apr 02:13:11 - [970] reading config file: ./config/config.js
documentserver_1  | 1 Apr 02:13:11 - server is up INFO
documentserver_1  | 1 Apr 02:20:40 - [997] reading config file: ./config/config.js
documentserver_1  | 1 Apr 02:20:41 - server is up INFO
documentserver_1  |
documentserver_1  | ==> /var/log/onlyoffice/documentserver/nginx.error.log <==
documentserver_1  | 2021/04/01 01:59:01 [error] 1036#1036: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: , request: "GET /6.2.0-123/doc/6145278353dd2aa01a70/c/info?t=
1617242340936 HTTP/1.1", upstream: "http://127.0.0.1:8000/doc/6145278353dd2aa01a70/c/info", host: "localhost", referrer: "http://localhost/6.2.0-123/web-apps/apps/documenteditor/main/index.html?_dc=6.2.0-123&lang=en&customer
=ONLYOFFICE&frameEditorId=editor&mode=view&parentOrigin=http://localhost:8080"
documentserver_1  | 2021/04/01 01:59:01 [error] 1036#1036: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: , request: "GET /6.2.0-123/doc/6145278353dd2aa01a70/c/info?t=
1617242340936 HTTP/1.1", upstream: "http://127.0.0.1:8000/doc/6145278353dd2aa01a70/c/info", host: "localhost", referrer: "http://localhost/6.2.0-123/web-apps/apps/documenteditor/main/index.html?_dc=6.2.0-123&lang=en&customer
=ONLYOFFICE&frameEditorId=editor&mode=view&parentOrigin=http://localhost:8080"
documentserver_1  | 2021/04/01 02:23:10 [error] 1036#1036: *11 upstream prematurely closed connection while reading response header from upstream, client: 172.19.0.1, server: , request: "POST /6.2.0-123/doc/5251e33d66ce40944
116/c/277/2acemjjw/xhr?t=1617243765469 HTTP/1.1", upstream: "http://127.0.0.1:8000/doc/5251e33d66ce40944116/c/277/2acemjjw/xhr", host: "localhost", referrer: "http://localhost/6.2.0-123/web-apps/apps/documenteditor/main/inde
x.html?_dc=6.2.0-123&lang=en&customer=ONLYOFFICE&frameEditorId=editor&mode=view&parentOrigin=http://localhost:7070"
documentserver_1  |
documentserver_1  | ==> /var/log/onlyoffice/documentserver/spellchecker/err.log <==
documentserver_1  |
documentserver_1  | ==> /var/log/onlyoffice/documentserver/spellchecker/out.log <==
documentserver_1  | [2021-04-01T02:06:44.128] [WARN] nodeJS - Express server starting...
documentserver_1  | [2021-04-01T02:06:44.158] [WARN] nodeJS - Express server listening on port 8080 in production-linux mode
documentserver_1  | [2021-04-01T02:13:11.603] [WARN] nodeJS - start cluster with 1 workers
documentserver_1  | [2021-04-01T02:13:11.942] [WARN] nodeJS - worker 1015 started.
documentserver_1  | [2021-04-01T02:13:14.672] [WARN] nodeJS - Express server starting...
documentserver_1  | [2021-04-01T02:13:14.713] [WARN] nodeJS - Express server listening on port 8080 in production-linux mode
documentserver_1  | [2021-04-01T02:20:40.927] [WARN] nodeJS - start cluster with 1 workers
documentserver_1  | [2021-04-01T02:20:41.271] [WARN] nodeJS - worker 1043 started.
documentserver_1  | [2021-04-01T02:20:52.900] [WARN] nodeJS - Express server starting...
documentserver_1  | [2021-04-01T02:20:53.040] [WARN] nodeJS - Express server listening on port 8080 in production-linux mode
documentserver_1  |
documentserver_1  | ==> /var/log/onlyoffice/documentserver/converter/out.log <==
documentserver_1  | [2021-04-01T02:23:31.626] [ERROR] nodeJS - error downloadFile:url=http://localhost:7070/files/sample.docx;attempt=2;code:ECONNREFUSED;connect:null;(id=635ea88559c288a4e6da)
documentserver_1  | Error: connect ECONNREFUSED 127.0.0.1:7070
documentserver_1  |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
documentserver_1  | [2021-04-01T02:23:32.628] [ERROR] nodeJS - error downloadFile:url=http://localhost:7070/files/sample.docx;attempt=3;code:ECONNREFUSED;connect:null;(id=635ea88559c288a4e6da)
documentserver_1  | Error: connect ECONNREFUSED 127.0.0.1:7070
documentserver_1  |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
app_1             | 172.19.0.1 - - [01/Apr/2021 02:24:16] "GET /files/sample.pptx;attempt=2;code:ECONNREFUSED;connect:null HTTP/1.1" 404 786
app_1             | 172.19.0.1 - - [01/Apr/2021 02:24:26] "GET /files/sample.pptx HTTP/1.1" 200 1130088`

I think I should define a different host for the app and editor services.

Any help will be appreciate it!!!!

**Comment by flaminestone** [comment]
Hello @JDSalcedo. You need to use ip addres of your host machine in config file (`editor.url` and `app.url`), not `localhost` word, because localhost inside of docker container is not the same of localhost of your machin.
Try to change this, I hope it help

**Comment by JDSalcedo** [comment]
Thanks for your replay @flaminestone you were right, thanks a lot.
